services:
  superset:
    image: apache/superset:4.1.2
    container_name: superset
    env_file:
      - ../../.env
    ports:
      - "8088:8088"
    environment:
      SUPERSET_ENV: production
      SUPERSET_LOAD_EXAMPLES: "no"
      # SUPERSET_SECRET_KEY: "change-me"
      SUPERSET_SECRET_KEY: K0xI1PtWszpq3eaVJ5f5s4wTs0MYdUC1uY7XT5MjZtHhqeeH8p==
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      ADMIN_EMAIL: admin@example.com
    volumes:
      - superset_home:/app/superset_home
    command: ["/bin/sh","-c","superset db upgrade && superset fab create-admin --username \"$ADMIN_USERNAME\" --firstname Admin --lastname User --email \"$ADMIN_EMAIL\" --password \"$ADMIN_PASSWORD\" || true && superset init && gunicorn -w 2 --threads 20 --timeout 120 -b 0.0.0.0:8088 'superset.app:create_app()'"]
volumes:
  superset_home:
